import localFont from 'next/font/local'
import './globals.css'

const amikoFont = localFont({
  src: [
    {
      path: '../public/fonts/Amiko-Bold-webfont.woff',
      weight: '700',
      style: 'bold'
    },
    {
      path: '../public/fonts/Amiko-Regular-webfont.woff',
      weight: '400',
      style: 'normal'
    },
    {
      path: '../public/fonts/Amiko-SemiBold-webfont.woff',
      weight: '600',
      style: 'semibold'
    }
  ]
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={amikoFont.className}>{children}</body>
    </html>
  )
}
